SET SESSION sql_mode="NO_ENGINE_SUBSTITUTION";


-- FINDING THE AVERAGE DEPARTURE FLIGHT DELAY BY AIRLINE
select 
AI.AIRLINE
,AI.IATA_CODE
,ROUND(AVG(F.DEPARTURE_DELAY)) AS AVERAGE_DEPARTURE_FLIGHT_DELAY
from flights F JOIN AIRLINES AI ON F.AIRLINE = AI.IATA_CODE
GROUP BY F.AIRLINE
ORDER BY AVERAGE_DEPARTURE_FLIGHT_DELAY DESC;

-- FINDING THE AVERAGE DEPARTURE FLIGHT DELAY BY AIRPORT
SELECT 
ORIGIN_AIRPORT
,ROUND(AVG(DEPARTURE_DELAY)) AS AVERAGE_DEPARTURE_FLIGHT_DELAY
FROM FLIGHTS
WHERE ORIGIN_AIRPORT NOT LIKE('%1%')
GROUP BY ORIGIN_AIRPORT
ORDER BY AVERAGE_DEPARTURE_FLIGHT_DELAY DESC;

CREATE TABLE DELAY_BY_AIRPORT

SELECT 
ORIGIN_AIRPORT
,ROUND(AVG(DEPARTURE_DELAY)) AS AVERAGE_DEPARTURE_FLIGHT_DELAY
FROM FLIGHTS
WHERE ORIGIN_AIRPORT NOT LIKE('%1%')
GROUP BY ORIGIN_AIRPORT
ORDER BY AVERAGE_DEPARTURE_FLIGHT_DELAY DESC;

-- FINDING THE AVERAGE DEPATURE DELAY TIME BY AIRLINE AT EACH AIRPORT
SELECT 
F.ORIGIN_AIRPORT
,AI.AIRLINE
,AI.IATA_CODE
,ROUND(AVG(F.DEPARTURE_DELAY)) AS AVERAGE_DEPARTURE_FLIGHT_DELAY
,D.AVERAGE_DEPARTURE_FLIGHT_DELAY
FROM FLIGHTS F 
JOIN AIRLINES AI ON F.AIRLINE = AI.IATA_CODE
JOIN DELAY_BY_AIRPORT D ON F.ORIGIN_AIRPORT = D.ORIGIN_AIRPORT
WHERE F.ORIGIN_AIRPORT NOT LIKE('%1%')
GROUP BY AI.AIRLINE, F.ORIGIN_AIRPORT
ORDER BY F.ORIGIN_AIRPORT ASC, AVERAGE_DEPARTURE_FLIGHT_DELAY DESC;



-- ARE FLIGHTS AT A CERTAIN TIME MORE PRONE TO DELAYS? COULD I GROUP BY HOUR?
SELECT 
CAST(ROUND(CAST(SCHEDULED_DEPARTURE AS TIME),-2)*100 AS TIME) AS HOUR_OF_DAY
,ROUND(AVG(DEPARTURE_DELAY)) AVERAGE_DEPARTURE_DELAY
FROM FLIGHTS
GROUP BY HOUR_OF_DAY;

-- ARE CERTAIN DAYS OF THE WEEK MORE PRONE TO DELAYS?
DROP IF EXISTS DAYS_OF_WEEK;

CREATE TABLE DAYS_OF_WEEK
SELECT
CONCAT(YEAR,"-",MONTH,"-",DAY) AS DATE1
,DEPARTURE_DELAY
FROM FLIGHTS;

SELECT
DAYNAME(DATE1) AS DAY
,ROUND(AVG(DEPARTURE_DELAY)) AS AVERAGE_DEPARTURE_DELAY
FROM DAYS_OF_WEEK
GROUP BY DAY;



